RDKCOM-2926 RDKCMF-8827: ctrlm-main build failure
ctrlm-main build is failing in Broadcom Reference platforms:
In file included from ../../git/src/ctrlm.h:33,
 from ../../git/src/database/ctrlm_db_attr.h:23,
 from ../../git/src/database/ctrlm_db_types.h:23,
 from ../../git/src/database/ctrlm_db_types.cpp:20:
../../git/src/database/ctrlm_db_types.cpp: In member function 'bool ctrlm_db_blob_t::from_buffer(char*, size_t)':
../../git/src/ctrlm_log.h:61:91: error: format '%s' expects a matching 'char*' argument [-Werror=format=]
 61 | #define LOG(FORMAT, ...); {char log_buffer[13]; ctrlm_get_log_time(log_buffer); printf("%s " FORMAT, log_buffer, ##__VA_ARGS__);}
../../git/src/ctrlm_log.h:104:27: note: in expansion of macro 'LOG'
 104 | #define LOG_WARN(...) LOG(LOG_PREFIX_WARN __VA_ARGS__)
 | ^~~
../../git/src/database/ctrlm_db_types.cpp:159:13: note: in expansion of macro 'LOG_WARN'
 159 | LOG_WARN("%s: empty buffer");
 | ^~~~~~~~
../../git/src/database/ctrlm_db_types.cpp:159:24: note: format string is defined here
 159 | LOG_WARN("%s: empty buffer");
 | ~^
 | |
 | char*
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:1282: database/ctrlm_db_types.o] Error 1

Reason for change: RDKCMF-8827: ctrlm-main build failure
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 285f019473de52a8f7d25569d45d495b0f17e656)
Change-Id: Iad8770afe63b43270a6f6907c2b3518bf2d6d02d